# Generated by Django 3.1.2 on 2020-11-01 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0005_employeer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='mobile',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
