# Generated by Django 3.1.2 on 2020-10-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='username',
        ),
        migrations.AddField(
            model_name='employeer',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
