# Generated by Django 3.1.2 on 2020-11-01 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0002_auto_20201031_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='password',
        ),
    ]
