# Generated by Django 3.1.2 on 2020-11-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
    ]
